server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/git4ang/eCinema_microservices_configRepos
          clone-on-start: true
          default-label: main
          basedir: target/configRepos
          username: config
          password: 1234
  profiles:
    active: dev, default, test

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/admin"
  endpoint:
    health:
      show-details: always
    env:
      post:
        enabled: true

logging:
  level:
    org.springframework.cloud: DEBUG